// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crpc_protocol.proto

package com.github.leeyazhou.grpc;

public final class CrpcProtocol {
  private CrpcProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestGrpcMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestGrpcMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseGrpcMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseGrpcMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023crpc_protocol.proto\"(\n\022RequestGrpcMess" +
      "age\022\022\n\ninvocation\030\001 \001(\014\"\'\n\023ResponseGrpcM" +
      "essage\022\020\n\010response\030\001 \001(\0142F\n\016MessageServi" +
      "ce\0224\n\007request\022\023.RequestGrpcMessage\032\024.Res" +
      "ponseGrpcMessageB+\n\031com.github.leeyazhou" +
      ".grpcB\014CrpcProtocolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestGrpcMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestGrpcMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestGrpcMessage_descriptor,
        new java.lang.String[] { "Invocation", });
    internal_static_ResponseGrpcMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseGrpcMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseGrpcMessage_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
