// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crpc_protocol.proto

package com.github.leeyazhou.grpc;

/**
 * Protobuf type {@code RequestGrpcMessage}
 */
public final class RequestGrpcMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RequestGrpcMessage)
    RequestGrpcMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestGrpcMessage.newBuilder() to construct.
  private RequestGrpcMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestGrpcMessage() {
    invocation_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestGrpcMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestGrpcMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            invocation_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.leeyazhou.grpc.CrpcProtocol.internal_static_RequestGrpcMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.leeyazhou.grpc.CrpcProtocol.internal_static_RequestGrpcMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.leeyazhou.grpc.RequestGrpcMessage.class, com.github.leeyazhou.grpc.RequestGrpcMessage.Builder.class);
  }

  public static final int INVOCATION_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString invocation_;
  /**
   * <code>bytes invocation = 1;</code>
   * @return The invocation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getInvocation() {
    return invocation_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!invocation_.isEmpty()) {
      output.writeBytes(1, invocation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!invocation_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, invocation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.leeyazhou.grpc.RequestGrpcMessage)) {
      return super.equals(obj);
    }
    com.github.leeyazhou.grpc.RequestGrpcMessage other = (com.github.leeyazhou.grpc.RequestGrpcMessage) obj;

    if (!getInvocation()
        .equals(other.getInvocation())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INVOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getInvocation().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.leeyazhou.grpc.RequestGrpcMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.leeyazhou.grpc.RequestGrpcMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RequestGrpcMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RequestGrpcMessage)
      com.github.leeyazhou.grpc.RequestGrpcMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.leeyazhou.grpc.CrpcProtocol.internal_static_RequestGrpcMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.leeyazhou.grpc.CrpcProtocol.internal_static_RequestGrpcMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.leeyazhou.grpc.RequestGrpcMessage.class, com.github.leeyazhou.grpc.RequestGrpcMessage.Builder.class);
    }

    // Construct using com.github.leeyazhou.grpc.RequestGrpcMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      invocation_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.leeyazhou.grpc.CrpcProtocol.internal_static_RequestGrpcMessage_descriptor;
    }

    @java.lang.Override
    public com.github.leeyazhou.grpc.RequestGrpcMessage getDefaultInstanceForType() {
      return com.github.leeyazhou.grpc.RequestGrpcMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.leeyazhou.grpc.RequestGrpcMessage build() {
      com.github.leeyazhou.grpc.RequestGrpcMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.leeyazhou.grpc.RequestGrpcMessage buildPartial() {
      com.github.leeyazhou.grpc.RequestGrpcMessage result = new com.github.leeyazhou.grpc.RequestGrpcMessage(this);
      result.invocation_ = invocation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.leeyazhou.grpc.RequestGrpcMessage) {
        return mergeFrom((com.github.leeyazhou.grpc.RequestGrpcMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.leeyazhou.grpc.RequestGrpcMessage other) {
      if (other == com.github.leeyazhou.grpc.RequestGrpcMessage.getDefaultInstance()) return this;
      if (other.getInvocation() != com.google.protobuf.ByteString.EMPTY) {
        setInvocation(other.getInvocation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.leeyazhou.grpc.RequestGrpcMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.leeyazhou.grpc.RequestGrpcMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString invocation_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes invocation = 1;</code>
     * @return The invocation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getInvocation() {
      return invocation_;
    }
    /**
     * <code>bytes invocation = 1;</code>
     * @param value The invocation to set.
     * @return This builder for chaining.
     */
    public Builder setInvocation(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      invocation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes invocation = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvocation() {
      
      invocation_ = getDefaultInstance().getInvocation();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RequestGrpcMessage)
  }

  // @@protoc_insertion_point(class_scope:RequestGrpcMessage)
  private static final com.github.leeyazhou.grpc.RequestGrpcMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.leeyazhou.grpc.RequestGrpcMessage();
  }

  public static com.github.leeyazhou.grpc.RequestGrpcMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestGrpcMessage>
      PARSER = new com.google.protobuf.AbstractParser<RequestGrpcMessage>() {
    @java.lang.Override
    public RequestGrpcMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestGrpcMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestGrpcMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestGrpcMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.leeyazhou.grpc.RequestGrpcMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

