// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crpc_protocol.proto

package com.github.leeyazhou.grpc;

public interface RequestGrpcMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestGrpcMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes invocation = 1;</code>
   * @return The invocation.
   */
  com.google.protobuf.ByteString getInvocation();
}
