// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crpc_protocol.proto

package com.github.leeyazhou.grpc;

public interface ResponseGrpcMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseGrpcMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes response = 1;</code>
   * @return The response.
   */
  com.google.protobuf.ByteString getResponse();
}
